### ISSUE TITLE
FPWD Feedback from Ege Korkan

### ISSUE THREAD

**Issue by egekorkan** [w3c/wot-profile#37] opened 2020-10-05 11:51 UTC
Please find below my feedback on the GH version of 03.10.2020:

### Property Affordance

- Why not allow const? It makes sense in the key of an object. Hue devices use a lot of const in objects to denote model numbers in payloads
- Why enum only simple type? if I can use type object, it should be possible to use in enum
-  _The Array of Form of each property MUST contain only a single endpoint for each operation readproperty , writeproperty , observeproperty , unobserveproperty._   -> An operation should be associatable only with one form
- Remove format requirement -> Not in JSON Schema
- _oneOf does not make sense_ -> sense is a vague and subjective term. I agree with this requirement but this should be more specific and objective
- type is a must -> What about photos etc.? Adding an "if" condition that says if JSON than yes, otherwise no. 
	- After reading the rest, there is a restriction in JSON. This restriction should be made before the restriction on the DataSchema otherwise many things make less sense.
- Should there be an assertion saying terms not in TD are not allowed for DataSchema, i.e. anyOf

5.1.5 -> Should be Action Affordance

### Action Affordance

- Why input allows only simple types?
- Remove format requirement -> Not in JSON Schema
- oneOf text contains properties word. Does this "make sense" apply to action the same way?

### Event Affordance

- Why those types in events?
- forms -> saying that both sub and unsub op should be present in there

### Forms

- What is "data" in forms?

### Security

- OAuth2 -> Should all scopes be supported?
- Basic -> Should all "in" values be allowed -> No one in the group has implemented cookie for example

### HTTP Binding

- The events section is way too loose to allow out-of-the-box-interop (OOTBI). With WS in there, OOTBI is impossible, similar-ish with WebHooks. No experience at all with both of them from the plugfests. If this spec is not bringing OOTBI, its main argument to exist becomes less obvious.
- Any restriction in subprotocols? 
- _The supported protocols for events are_ -> Should be supported subprotocols since we are talking about HTTP already

### General Feedback

- There are no examples at all.
- Why is Data Schema constraints depend on the interaction affordance type? I have remarks on this in each Interaction Affordance.

**Comment by benfrancis** [comment] 2021-11-04 17:20
@egekorkan I think the issues with the HTTP binding have now been addressed. Should we mark the remainder of this issue as a duplicate of #3?

**Comment by egekorkan** [comment] 2021-11-05 17:07
I would say that my concerns are almost satisfied. Remaining are:
- `data` in Forms is still present.
- OAuth2 having all scopes/styles?
- No examples of TDs with core profile
- Eventing is still not fixed but I think we have enough issues on this particular point

**Closed** 2022-09-28 08:16 UTC
Labels: FPWD Feedback, close

**Comment by egekorkan** [comment] 2022-09-28 09:49
I think that my concern regarding Oauth2 is not addressed. But I have found #41 that talks about this so I will move my comment there
