### ISSUE TITLE
Allow only a finite set of vocabulary extensions?

### ISSUE THREAD

**Issue by mlagally** [w3c/wot-profile#30] opened 2020-08-27 15:17 UTC
Arch call on Aug 27.8.:
@Context extensions should be a finite list of URLs, e.g. iotschema.org, qudt, but no arbitrary RDF.

This would allow a prebaked context that does not require dynamic parsing of context files, which may be privacy sensitive. Also we want to limit implementation complexity.

We may have to pick specific versions of referenced context files, i.e. take snapshots or refer to a stable released version.

**Comment by mlagally** [comment] 2020-09-17 15:56
Before we have a referencable public document from OneDM, we can use IoTSchema.org as a placeholder.
For units we discussed SenML and qudt.

-> need to create a single paragraph as part of chapter

We also need to specify a prefix for each of the vocabulary extensions.

**Comment by benfrancis** [comment] 2021-11-04 17:13
I don't think any repository of capability schemas (OneDM, iotschema.org, webthings.io/schemas) is going to be mature enough to require support for it in version 1 of the Core Profile.

I suggest deferring to 2.0 or closing as a duplicate of #29.

**Comment by benfrancis** [comment] 2022-09-21 15:44
I suggest we consider re-visiting this for WoT Profile 2.0, see also #285.

**Closed** 2022-09-28 08:17 UTC
Labels: close
