### ISSUE TITLE
Events need a way to express timestamps

### ISSUE THREAD

**Issue by mlagally** [w3c/wot-profile#100] opened 2021-09-16 15:13 UTC
The event model currently does not define a common way of signaling events with time stamps.

These could be part of the object payload or be a part of the format we do in the id.
A standardized time stamp format on events provides enhanced interoperability.
One apporach could be to define a wrapper object around the event payload.

**Comment by egekorkan** [comment] 2021-11-04 16:20
Is it about when the event actually happened? Otherwise, when the Consumer receives the event, it can use its own timestamp or in the case of HTTP, use the timestamp in the header?

**Comment by benfrancis** [comment] 2021-11-04 17:58
@egekorkan There is no HTTP header for an individual event because in SSE the connection just stays open and events are streamed over the TCP socket. What there is however is an `id` on each event, for which a timestamp (number of milliseconds past the epoch) is often used. This is so that an easy comparison can be made with a `Last-Event-ID` header upon reconnecting a dropped connection.

In my view this `id` field the best place to put a timestamp in SSE. If we try to expand the JSON data schema of an event payload (the `data` field in SSE) beyond the schema defined in the `data` member of an event affordance, things are going to get complicated.

**Comment by mlagally** [comment] 2021-11-10 10:46
See discussion in #101

**Comment by mlagally** [comment] 2021-11-10 10:54
The structured JSON event format of the cloud events spec should be considered for the event payload.
It contains attribute names for time stamps and other relevant metadata. 

https://github.com/cloudevents/spec/blob/v1.0.1/json-format.md

**Comment by benfrancis** [comment] 2021-11-10 12:17
> The structured JSON event format of the cloud events spec should be considered for the event payload.

I don't think that's a good idea.

1. The events protocol binding uses Server-Sent Events which have their own text-based payload format, defined in a W3C specification. Wrapping the data part of that payload in an additional JSON payload format will complicate things unnecessarily.
2. CloudEvents are not a referenceable standard, see #126 

Below is an example of an event payload using the current Server-Sent Events protocol binding:

```
event: overheated\n
data: 90\n
id: 2021-11-10T11:43:19Z\n\n
```

Below is an example of that same event payload, but with the additional CloudEvents wrapper (based on my quick read of the specification):

```
event: overheated\n
data: {\n
data:    "specversion" : "1.0",\n
data:    "type" : "io.webthings.schemas.overheated",\n
data:    "source" : "https://mythingserver.com/things/lamp",\n
data:    "subject" : "overheated",\n
data:    "id" : "2021-11-10T11:43:19Z",\n
data:    "time" : "2021-11-10T11:43:19Z",\n
data:    "datacontenttype" : "application/json",\n
data:    "data" : "90"\n
data: }\n
id: 2021-11-10T11:43:19Z\n\n
```

Hopefully it's self-evident that this just significantly increases the size of the payload and duplicates a lot of data, without actually providing the Consumer with any additional information which it doesn't already have.

Another more general problem with wrapping one payload format inside another is that the `data` part of the event payload no longer maps directly onto the schema provided in the `data` member of the event affordance in the Thing Description. Describing the Server-Sent Events payload in the Thing Description is a simple matter of adding `"subprotocol": "sse"` to the Form. I'm not sure how a CloudEvent wrapped in a Server-Sent Event could be described in a Thing Description.

**Comment by egekorkan** [comment] 2021-11-10 12:31
> I'm not sure how a CloudEvent wrapped in a Server-Sent Event could be described in a Thing Description.

It is definitely possible. It would be JSON Schema with multiple properties, something a bit more restricted than what is below:

```json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "type": "object",
  "properties": {
    "specversion": {
      "type": "string"
    },
    "type": {
      "type": "string"
    },
    "source": {
      "type": "string"
    },
    "subject": {
      "type": "string"
    },
    "id": {
      "type": "string"
    },
    "time": {
      "type": "string"
    },
    "datacontenttype": {
      "type": "string"
    },
    "data": {
      "type": "string"
    }
  },
  "required": [
    "specversion",
    "type",
    "source",
    "subject",
    "id",
    "time",
    "datacontenttype",
    "data"
  ]
}
```

This would have to be either in every `data` value of the event or use the soon to be there `schemaDefinitions` and referenced from there. In any case, I don't see a real benefit of using this. CloudEvents makes sense when you don't have a good way of knowing how different events are generated or where they are coming from when you want to aggregate them for event processing pipelines. We already have TDs and I don't see a good reason to bake in CloudEvents for green field use cases.

**Comment by benfrancis** [comment] 2021-11-10 12:56
@egekorkan I thought something like that might be necessary, but the problem is that if you set the `data` member of an event affordance to the data schema of a CloudEvent, where do you put the data schema of the actual event data? Presumably you'd have to nest it inside the `data` property of the CloudEvent schema. That would then require repeating the CloudEvent schema in every event affordance, since each one would be different [1].

All of this _could_ be defined in the prose of the Core Profile protocol binding specification rather than declaratively in a Thing Description, but so far I don't see any justification for this added complexity.

I have already submitted a PR (#119) which fulfils this requirement in a much simpler way by simply recommending that Producers use a timestamp as an event ID (which is already a common practice in Server-Sent Events). I welcome feedback on that PR.

--- 

1. As I understand it `schemaDefinitions` can currently only be used in an `AdditionalExpectedResponse` anyway, they can't be used in the `data` member of an `EventAffordance`. I have proposed that they should also be useable in an `ExpectedResponse`, but that hasn't happened yet.

**Comment by egekorkan** [comment] 2021-11-10 13:13
> Presumably you'd have to nest it inside the data property of the CloudEvent schema. That would then require repeating the CloudEvent schema in every event affordance, since each one would be different [1].

Yes and yes. This `schemaDefinitions` will be in 1.1 afaik. 

> All of this could be defined in the prose of the Core Profile protocol binding specification

This would be a solution.

> but so far I don't see any justification for this added complexity.

I agree with this

**Comment by mlagally** [comment] 2021-11-10 15:53
@egekorkan 
I like the schema definition you are proposing and think it is the right approach.
We have structured data everywhere and I'm a bit concerned if we tweak SSE id's and the like to contain actual metadata values, such as time stamps etc. 

If we assume that many consumers are implemented in TypeScript / JavaScript,
processing a JSON event object is very natural.
Encoding a JSON object in a string is also straightforward, so I thought it would be 
very easy to adopt.

If we look at the specific metadata fields, these make a lot sense to add, 
since they provide additional structure:

- specversion - good practice to indicate the TD spec version, ensure compatibility 
- type
- source - reference to the originator
- id - unique event id
- time - time in standard time format 
- data  - structured message data
- dataContentType 

@benfrancis 
I think your example is very useful to illustrate the added value of structured event data
and a JSON event object, that can be directly used by the consumer as it is without any further processing:

```
event: overheated\n
data: {\n
data:    "specversion" : "1.0",\n
data:    "type" : "io.webthings.schemas.overheated",\n
data:    "source" : "https://mythingserver.com/things/lamp",\n
data:    "subject" : "overheated",\n
data:    "id" : "2021-11-10T11:43:19Z",\n
data:    "time" : "2021-11-10T11:43:19Z",\n
data:    "datacontenttype" : "application/json",\n
data:    "data" : "90"\n
data: }\n
id: 2021-11-10T11:43:19Z\n\n
```

- It can handle different event types
- it already includes the source object
- it supports versioning
- it supports different data types

As usual the most simple approach is most tempting, and just having string data in an unstructured sequence of lines (SSE) is very simple. However I expect will have to extend it to iteratively  introduce these other metadata fields.

I was also thinking a bit ahead and am convinced that a clear decoupling of the event transport mechanism (SSE, WebHooks, ...) from the event object (=payload) will be more future proof, also for other protocol bindings and profiles.

**Comment by benfrancis** [comment] 2021-11-10 19:04
It appears that the issues are not self-evident after all, so I'll explain my thinking further.

@mlagally wrote:
> I'm a bit concerned if we tweak SSE id's and the like to contain actual metadata values, such as time stamps etc.

This isn't tweaking anything. As I have already mentioned, using timestamps as IDs is  common practice in SSE.

> If we assume that many consumers are implemented in TypeScript / JavaScript,
> processing a JSON event object is very natural.

Most modern programming languages can parse JSON. I agree that processing a JSON event object is a good fit for an HTTP+JSON protocol binding.

> Encoding a JSON object in a string is also straightforward, so I thought it would be
> very easy to adopt.

I agree, but you seem to have misunderstood the current protocol binding. The event payload (data field) is _already_ JSON encoded as a string. See [section 5.2.3.1 `subscribeevent`](https://w3c.github.io/wot-profile/#subscribeevent) of the specification:

>> The event data MUST follow the data schema specified in the EventAffordance and MUST be serialized in JSON.

The data schema from the `data` member of an event affordance is mapped directly on to the `data` field of the SSE event.

 In the example the data schema of the event has a type of number:

```
    "overheated": {
      "title": "Overheated",
      "data": {
        "type": "number",
        "unit": "degree celsius"
      }
    }
```
Which is mapped directly onto the data field of the SSE event:

```
event: overheated\n
data: 90\n
id: 2021-11-10T11:43:19Z\n\n
```

If the data schema was an object, e.g.:

```
    "touch": {
      "title": "Touch",
      "description": "The screen was touched",
      "data": {
        "type": "object",
        "properties": {
          "screenX": {
            "type": "number"
          },
          "screenY": {
            "type": "number"
          }
        }
      }
    }
```

then the data field in the event would be a serialised object:

```
event: touch\n
data: {"screenX": 53, "screenY": 26}
id: 2021-11-10T11:43:19Z\n\n
```

> If we look at the specific metadata fields, these make a lot sense to add, since they provide additional structure:
> 
>  * specversion - good practice to indicate the TD spec version, ensure compatibility

This is already provided by the Thing Description, it's wasteful to include it in every event payload.

>  * type

This is already provided in the Thing Description.

>  * source - reference to the originator

This is implicit in the protocol binding since the URL of the event stream is the URL of the event.

>  * id - unique event id

The event payload already contains an ID.

>  * time - time in standard time format

It is common practice to set the ID to a timestamp.

>  * data  - structured message data

There is already a data field in the event payload which provides structured message data (explained above).

>  * dataContentType

The data content type is guaranteed to always be JSON, which is fundamental to providing interoperability.

> I think your example is very useful to illustrate the added value of structured event data
> and a JSON event object, that can be directly used by the consumer as it is without any further processing:

As I have explained above, this is already the case.

> * It can handle different event types

SSE has an event field which is used to provide the name of the event.

> * it already includes the source object

This is implicit in the URL of the event stream.

> * it supports versioning

This is already included in the Thing Description.

> * it supports different data types

This is not a desirable property for a prescriptive profile.


> As usual the most simple approach is most tempting

With good reason, in my opinion.

> and just having string data in an unstructured sequence of lines (SSE) is very simple. However I expect will have to extend it to iteratively introduce these other metadata fields.

As I have explained above, it is a misunderstanding that SSE only provides unstructured text as the payload is JSON. The SSE standard already provides everything we need and maps very neatly onto the WoT data model. I don't see the need to wrap one payload format in another to communicate the same information in a more complex way.

> I was also thinking a bit ahead and am convinced that a clear decoupling of the event transport mechanism (SSE, WebHooks, ...) from the event object (=payload) will be more future proof, also for other protocol bindings and profiles.

Ah, now I see the reason for overcomplicating the solution. You want it to be protocol agnostic. I'd say that is the complete opposite of the goal of the Core Profile, which aims to provide a prescriptive solution that works best for one protocol (HTTP). Providing multiple options for an event mechanism inside a single profile (e.g. SSE and WebHooks) would work _against_ the goal of interoperability since different Things would use different event mechanisms. I have explained in #107 why I don't think requiring support for WebHooks is a good idea, since it will require every conformant Consumer to be both a web client and a web server.

I am also very confused about why you continue to push for data model constraints which reduce the size of the metadata in Thing Descriptions to help constrained metadata, whilst simultaneously arguing for a data payload format which communicates the same information but requires several times the number of bytes to do so.

As a reminder, this issue is just about adding timestamps to the events protocol binding. I have submitted a PR which solves that problem in a single sentence. There's really no need to adopt a whole new (non-standard) event payload specification in order to achieve that. In my view that would be massively over-engineered.

**Closed** 2022-08-03 11:43 UTC
Labels: blocks publication
